### ISSUE TITLE
The Markdowner Class is missing from the Tests/Services folder

### ISSUE THREAD

**Issue by 0xgdr** [ChuckHeintzelman/l5beauty#2]
I am following along with your code examples from the book and I can't get my test to go green looking at p59 of the book there should be a Markdowner Class in the Tests/Services folder but its missing.

**Comment by ChuckHeintzelman** [comment]
I'm assuming you're talking the PDF version of the book. On page 58 you create a 'tests/Services/MarkdownerTest.php' file which should have an error until you create the 'app/Services/Markdowner.php' class on page 59.

I'd double-check and make the sure one in the 'tests/Services' directory is named 'MarkdownerTest' and the one in the 'app/Services' is named 'Markdowner'
