### ISSUE TITLE
Validation rules message

### ISSUE THREAD

**Issue by anhtuank7c** [ChuckHeintzelman/l5beauty#4]
Dear Chuck Heintzelman!
How to create validation message for myself at PostCreateRequest?
Ex: You must enter title field.

**Comment by ChuckHeintzelman** [comment]
You'd need to edit the message in "resources/lang/en/validation.php"

**Comment by anhtuank7c** [comment]
I did find out a trick.
At PostCreateRequest insert a function:

public function messages() {
    return ['title.required' => trans('message.your_message')];
}
